### ISSUE TITLE
L'interface de la consommation d'énergie ne change pas après installation

### ISSUE THREAD

**Issue by Plop** [hekmon/hatempotheme#1]
Bonsoir,

Après avoir suivi l'intégralité de la documentation (deux fois), je ne parviens toujours pas à profiter du thème, celui de HomeAssistant étant le seul apparaissant.

J'ai bien configuré le configuration.yaml, installé le thème (avec HACS la première fois, puis manuellement pour être certain que tout était bon), rechargé le thème, configuré le thème par défault ainsi que celui de l'utilisateur, et redémarré HomeAssistant, mais cela ne fonctionne pas.

Pouvez-vous m'aider ? Merci

**Comment by hekmon** [comment]
Bonjour,

Qu'entendez-vous par cela ne fonctionne pas ? Si vous avez pu le configurer par défault c'est bien qu'il a été reconnu par Home Assistant. Pourriez-vous partager un screenshot de votre dashboard Énergie ?

**Comment by pjeantaud** [comment]
Bonjour Edouard,

Je rencontre le même problème, après avoir suivi la configuration tel que décrit, le thème est bien créé, il est bien activé, mais il m'est impossible de lier les données de consommation Tempo dans le tableau de bord Energie. Qu'est ce qui me manque ? Merci !

**Comment by hekmon** [comment]
Bonjour,

Même réponse que la haut : pouvez-vous me poster une capteur d'écran de votre dashboard énergie ?

Je précise tout de même que ce thème n'est qu'un thème : il ne fait que changer les couleurs des compteurs. Ce n'est pas lui qui rappatrie les compteurs tempo dans le dashboard énergie : ca c'est une configuration utilisateur.

**Comment by pjeantaud** [comment]
Oui désolé, voici les copies d'écran.
![Capture d’écran 2024-02-21 à 18 58 52](https://github.com/hekmon/hatempotheme/assets/50436649/c18dc84a-2b0a-4e81-880c-4a6fc3c4c180)
![Capture d’écran 2024-02-21 à 18 59 46](https://github.com/hekmon/hatempotheme/assets/50436649/9290fc6d-28a2-4484-b2ae-ed093529ef71)
![Capture d’écran 2024-02-21 à 19 05 41](https://github.com/hekmon/hatempotheme/assets/50436649/1fe6c80e-bc33-402c-91f8-1d3193b4418a)

En fait je n'ai pas de sensor Energie qui prenne en compte Tempo et je me demande bien comment faire...
Ma source d'énergie réseau est un Shelly 3EM ; 1 canal pour le réseau, 1 canal pour l'onduleur et un canal pour le cumulus.

**Comment by pjeantaud** [comment]
Bonjour Edouard,

Le plus simple de ce que je comprends serait d'intégrer une interface TIC compatible avec votre repo linkytic ?

**Comment by pjeantaud** [comment]
Bonjour, une idée du pourquoi les couleurs ne sont pas affichées ?
J'ai posté la capture d'écran demandée.

**Comment by JPFOLLEGOT** [comment]
Bonjour,
En fait la sélection "Sélectionner le thème Tempo Énergie" ne se mémorise pas. 
Le thème "Tempo Energie" est bien visible et sélectionnable, mais le bouton "Appeler le service" n'a pas d'effet.
Si on quitte et revient sur "Home Assistant Frontend: Set the default theme" il est revenu à la valeur par défaut avec mode clair.

**Comment by hekmon** [comment]
@pjeantaud De ce que je vois vous n'avez qu'un seul compteur d'énergie (`Énergie Réseau` dans `Consommation du réseau`). Cette n'extension n'est qu'un theme qui colorise des compteurs déjà existant, les compteurs tempo doivent exister préalablement. Utiliser mon extension linkytic est une manière d'avoir ces compteurs effectivement.

@JPFOLLEGOT si la mise par défault ne fonctionne pas, vous pouvez le faire juste pour votre utilisateur dans votre profil utilisateur Home Assistant:
<img width="634" alt="image" src="https://github.com/user-attachments/assets/a9354cfa-4cac-4d57-9b7d-90772bb691a5">

**Comment by pjeantaud** [comment]
Bonjour,

> Le 14 nov. 2024 à 11:22, Edouard Hur ***@***.***> a écrit :
> 
> 
> @pjeantaud <https://github.com/pjeantaud> De ce que je vois vous n'avez qu'un seul compteur d'énergie (Énergie Réseau dans Consommation du réseau). Cette n'extension n'est qu'un theme qui colorise des compteurs déjà existant, les compteurs tempo doivent exister préalablement. Utiliser mon extension linkytic est une manière d'avoir ces compteurs effectivement.
> 
Merci de cette confirmation.
Je me demande juste comment intégrer la liaison TIC USB vers le RPI3B+ qui exécute Home Assistant.

EDIT : c'est bon j'ai trouvé comment faire, merci pour vos indications dans le README de LinkyTIC.

Cordialement,

Patrick
