### ISSUE TITLE
Création des compteurs couleurs dans le tableau de bord énergie

### ISSUE THREAD

**Issue by Tos26** [hekmon/hatempotheme#4]
Bonjour, 

Apparemment, j'inaugure les issues de ce dépot ;)

J'ai l'intégration Tempo https://github.com/hekmon/rtetempo et le suivi linky via https://github.com/bokub/ha-linky
Le thème est correctement installé et je l'ai sélectionné dans mon profil.
![image](https://github.com/user-attachments/assets/0639f0df-259b-4b6a-b364-c03c3e4d020e)

Cependant, je n'ai pas réussi à configurer les  différents compteurs comme décrit ici:
![image](https://github.com/user-attachments/assets/e3bb8ff9-7a80-426c-ad33-16f04307ab51)

Je peux créer une source liée à linky:
![image](https://github.com/user-attachments/assets/4c928341-9235-4ef9-9454-eeb1caaed166)

Mais ensuite, linky n'est plus proposé, vu que je l'ai déjà sélectionné:
![image](https://github.com/user-attachments/assets/733a8a38-19db-4a22-ab53-44a56c38d37e)

Je suppose que je n'ai pas vraiment compris la démarche. Serait-il possible de détailler la procédure ?

Merci d'avance.

**Comment by Simonlebucheron** [comment]
> Mais ensuite, linky n'est plus proposé, vu que je l'ai déjà sélectionné: ![image](https://private-user-images.githubusercontent.com/23366980/395819467-733a8a38-19db-4a22-ab53-44a56c38d37e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NzA0MjIsIm5iZiI6MTczNDc3MDEyMiwicGF0aCI6Ii8yMzM2Njk4MC8zOTU4MTk0NjctNzMzYThhMzgtMTlkYi00YTIyLWFiNTMtNDRhNTZjMzhkMzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA4MzUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMDU4YTU3NTBlYTgxMzg2MmM5NTY5Y2ZjNWEwNjFiZGI5YjY4NDIwNWViMmI5MjlmYjExOTQ2N2U4Y2NmZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eKA08D7uuxngcJ4aZguNxrbns7ef-Pve3C6tjT3hh4k)
> 
> Serait-il possible de détailler la procédure ?


Idem, même question pour moi,=)

**Comment by hekmon** [comment]
Bonjour,

Ce module n'est qu'un thème pour changer les couleurs des 6 premiers compteurs d'énergie de HA afin de les faire correspondre aux couleurs tempo. Il ne découpe en aucun cas un compteur unique en 6 compteurs ! Comme indiqué dans le [README](https://github.com/hekmon/hatempotheme?tab=readme-ov-file#usage):

> Ce thème se basant sur l'ordre des compteurs assurez-vous d'abord d'avoir configuré votre dashboard Énergie avec les compteurs dans l'ordre suivant :

Vous devez donc avoir au préalable les 6 compteurs existant dans Home Assistant pour que ce thème ne soit d'une quelconque utilité.

Sans le thème (couleurs par défault d'Home Assistant):
![image](https://github.com/user-attachments/assets/a5920e3c-652f-4254-b49a-f85603c8ee8b)

Avec le thème:
![image](https://github.com/user-attachments/assets/aed6fdd4-fb97-4654-99c7-5185d952a074)

C'est tout ce que ce module fait. Pour avoir les 6 compteurs vous devez utiliser une extension les récupérant tous les 6 (comme mon module [LinkyTIC](https://github.com/hekmon/linkytic) pour les connections TIC directes).

Concernant mon autre module [RTETempo](https://github.com/hekmon/rtetempo) il n'est en aucun lien lié à votre consommation ou à votre compteur Linky : il récupère simplement et au plus tôt les valeurs Tempo actuelles auprès de RTE. En amenant des informations supplémentaires il facilite la création de capteurs de prix qui peuvent être couplés avec des données de consommation.

En résumé :
- [LinkyTIC](https://github.com/hekmon/linkytic) (pour les connections TIC directes) permet de récupérer vos informations personnelles directement depuis votre compteur Linky (mais pas de prix donc que de la consommation et entre autres les 6 compteurs tempo)
- [RTETempo](https://github.com/hekmon/rtetempo) permet de récupérer les informations tempo directement depuis RTE et d'avoir celle du lendemain au plus tôt (vers 6h pour la première estimation et confirmation vers 11h) plutôt que d'attendre l'info du compteur vers 20h. Elle facilite la création de senseurs de prix qui peuvent ensuite être couplés avec les capteurs de consommation de la 1ère extension dans le dashboard énergie de Home Assistant
- [HATempoTheme](https://github.com/hekmon/hatempotheme) Cette extension permet simplement de donner un coup de peinture au dashboard énergie pour que les  6 premiers compteurs passent aux couleurs tempo

**Comment by Simonlebucheron** [comment]
Merci pour la précision. Je pensais qu’on pouvait interpréter les données de RTEtempo pour afficher les consommations correspondante pour chaque couleur de jour. Ça pourrait être une idée d’amélioration (entre ce projet et RTEtempo) ?

**Comment by Tos26** [comment]
C'est pareil, j'avais compris la même chose.
Merci pour les explications.
